#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Neutron\Console\Application;

// Use the custom NeutronApplication class
$application = new Application('Neutron Console', '1.0.0');

// Load commands from the external console routes file
if (file_exists(__DIR__ . '/src/console.php')) {
    require __DIR__ . '/src/console.php';
}

// Auto-load commands from the `src/Command` directory
foreach (glob(__DIR__ . '/src/Command/*.php') as $commandFile) {
    $commandClass = basename($commandFile, '.php');
    $fullyQualifiedClassName = "Neutron\\Command\\{$commandClass}";
    if (class_exists($fullyQualifiedClassName)) {
        $application->add(new $fullyQualifiedClassName());
    }
}

$application->run();